// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import Aerialway11 from './components/Aerialway11'
import Aerialway15 from './components/Aerialway15'
import Airfield11 from './components/Airfield11'
import Airfield15 from './components/Airfield15'
import Airport11 from './components/Airport11'
import Airport15 from './components/Airport15'
import AlcoholShop11 from './components/AlcoholShop11'
import AlcoholShop15 from './components/AlcoholShop15'
import AmericaFootball11 from './components/AmericaFootball11'
import AmericaFootball15 from './components/AmericaFootball15'
import AmusementPark11 from './components/AmusementPark11'
import AmusementPark15 from './components/AmusementPark15'
import Aquarium11 from './components/Aquarium11'
import Aquarium15 from './components/Aquarium15'
import ArtGallery11 from './components/ArtGallery11'
import ArtGallery15 from './components/ArtGallery15'
import Attraction11 from './components/Attraction11'
import Attraction15 from './components/Attraction15'
import Bakery11 from './components/Bakery11'
import Bakery15 from './components/Bakery15'
import Bank11 from './components/Bank11'
import Bank15 from './components/Bank15'
import Bar11 from './components/Bar11'
import Bar15 from './components/Bar15'
import Barrier11 from './components/Barrier11'
import Barrier15 from './components/Barrier15'
import Baseball11 from './components/Baseball11'
import Baseball15 from './components/Baseball15'
import Basketball11 from './components/Basketball11'
import Basketball15 from './components/Basketball15'
import Bbq11 from './components/Bbq11'
import Bbq15 from './components/Bbq15'
import Beer11 from './components/Beer11'
import Beer15 from './components/Beer15'
import Bicycle11 from './components/Bicycle11'
import Bicycle15 from './components/Bicycle15'
import BicycleShare11 from './components/BicycleShare11'
import BicycleShare15 from './components/BicycleShare15'
import BloodBank11 from './components/BloodBank11'
import BloodBank15 from './components/BloodBank15'
import Buddhism11 from './components/Buddhism11'
import Buddhism15 from './components/Buddhism15'
import Building11 from './components/Building11'
import Building15 from './components/Building15'
import BuildingAlt111 from './components/BuildingAlt111'
import BuildingAlt115 from './components/BuildingAlt115'
import Bus11 from './components/Bus11'
import Bus15 from './components/Bus15'
import Cafe11 from './components/Cafe11'
import Cafe15 from './components/Cafe15'
import Campsite11 from './components/Campsite11'
import Campsite15 from './components/Campsite15'
import Car11 from './components/Car11'
import Car15 from './components/Car15'
import Castle11 from './components/Castle11'
import Castle15 from './components/Castle15'
import Cemetery11 from './components/Cemetery11'
import Cemetery15 from './components/Cemetery15'
import Cinema11 from './components/Cinema11'
import Cinema15 from './components/Cinema15'
import Circle11 from './components/Circle11'
import Circle15 from './components/Circle15'
import CircleStroked11 from './components/CircleStroked11'
import CircleStroked15 from './components/CircleStroked15'
import City11 from './components/City11'
import City15 from './components/City15'
import ClothingStore11 from './components/ClothingStore11'
import ClothingStore15 from './components/ClothingStore15'
import College11 from './components/College11'
import College15 from './components/College15'
import Commercial11 from './components/Commercial11'
import Commercial15 from './components/Commercial15'
import Cricket11 from './components/Cricket11'
import Cricket15 from './components/Cricket15'
import Cross11 from './components/Cross11'
import Cross15 from './components/Cross15'
import Dam11 from './components/Dam11'
import Dam15 from './components/Dam15'
import Danger11 from './components/Danger11'
import Danger15 from './components/Danger15'
import Defibrillator11 from './components/Defibrillator11'
import Defibrillator15 from './components/Defibrillator15'
import Dentist11 from './components/Dentist11'
import Dentist15 from './components/Dentist15'
import Doctor11 from './components/Doctor11'
import Doctor15 from './components/Doctor15'
import DogPark11 from './components/DogPark11'
import DogPark15 from './components/DogPark15'
import DrinkingWater11 from './components/DrinkingWater11'
import DrinkingWater15 from './components/DrinkingWater15'
import Embassy11 from './components/Embassy11'
import Embassy15 from './components/Embassy15'
import EmergencyPhone11 from './components/EmergencyPhone11'
import EmergencyPhone15 from './components/EmergencyPhone15'
import Entrance11 from './components/Entrance11'
import Entrance15 from './components/Entrance15'
import EntranceAlt111 from './components/EntranceAlt111'
import EntranceAlt115 from './components/EntranceAlt115'
import Farm11 from './components/Farm11'
import Farm15 from './components/Farm15'
import FastFood11 from './components/FastFood11'
import FastFood15 from './components/FastFood15'
import Fence11 from './components/Fence11'
import Fence15 from './components/Fence15'
import Ferry11 from './components/Ferry11'
import Ferry15 from './components/Ferry15'
import FireStation11 from './components/FireStation11'
import FireStation15 from './components/FireStation15'
import Florist11 from './components/Florist11'
import Florist15 from './components/Florist15'
import Fuel11 from './components/Fuel11'
import Fuel15 from './components/Fuel15'
import Gaming11 from './components/Gaming11'
import Gaming15 from './components/Gaming15'
import Garden11 from './components/Garden11'
import Garden15 from './components/Garden15'
import GardenCenter11 from './components/GardenCenter11'
import GardenCenter15 from './components/GardenCenter15'
import Gift11 from './components/Gift11'
import Gift15 from './components/Gift15'
import Golf11 from './components/Golf11'
import Golf15 from './components/Golf15'
import Grocery11 from './components/Grocery11'
import Grocery15 from './components/Grocery15'
import Hairdresser11 from './components/Hairdresser11'
import Hairdresser15 from './components/Hairdresser15'
import Harbor11 from './components/Harbor11'
import Harbor15 from './components/Harbor15'
import Heart11 from './components/Heart11'
import Heart15 from './components/Heart15'
import Heliport11 from './components/Heliport11'
import Heliport15 from './components/Heliport15'
import Home11 from './components/Home11'
import Home15 from './components/Home15'
import HorseRiding11 from './components/HorseRiding11'
import HorseRiding15 from './components/HorseRiding15'
import Hospital11 from './components/Hospital11'
import Hospital15 from './components/Hospital15'
import IceCream11 from './components/IceCream11'
import IceCream15 from './components/IceCream15'
import Industry11 from './components/Industry11'
import Industry15 from './components/Industry15'
import Information11 from './components/Information11'
import Information15 from './components/Information15'
import Karaoke11 from './components/Karaoke11'
import Karaoke15 from './components/Karaoke15'
import Landmark11 from './components/Landmark11'
import Landmark15 from './components/Landmark15'
import Landuse11 from './components/Landuse11'
import Landuse15 from './components/Landuse15'
import Laundry11 from './components/Laundry11'
import Laundry15 from './components/Laundry15'
import Library11 from './components/Library11'
import Library15 from './components/Library15'
import Lighthouse11 from './components/Lighthouse11'
import Lighthouse15 from './components/Lighthouse15'
import Lodging11 from './components/Lodging11'
import Lodging15 from './components/Lodging15'
import Logging11 from './components/Logging11'
import Logging15 from './components/Logging15'
import Marker11 from './components/Marker11'
import Marker15 from './components/Marker15'
import MarkerStroked11 from './components/MarkerStroked11'
import MarkerStroked15 from './components/MarkerStroked15'
import MobilePhone11 from './components/MobilePhone11'
import MobilePhone15 from './components/MobilePhone15'
import Monument11 from './components/Monument11'
import Monument15 from './components/Monument15'
import Mountain11 from './components/Mountain11'
import Mountain15 from './components/Mountain15'
import Museum11 from './components/Museum11'
import Museum15 from './components/Museum15'
import Music11 from './components/Music11'
import Music15 from './components/Music15'
import Natural11 from './components/Natural11'
import Natural15 from './components/Natural15'
import Park11 from './components/Park11'
import Park15 from './components/Park15'
import ParkAlt111 from './components/ParkAlt111'
import ParkAlt115 from './components/ParkAlt115'
import Parking11 from './components/Parking11'
import Parking15 from './components/Parking15'
import ParkingGarage11 from './components/ParkingGarage11'
import ParkingGarage15 from './components/ParkingGarage15'
import Pharmacy11 from './components/Pharmacy11'
import Pharmacy15 from './components/Pharmacy15'
import PicnicSite11 from './components/PicnicSite11'
import PicnicSite15 from './components/PicnicSite15'
import Pitch11 from './components/Pitch11'
import Pitch15 from './components/Pitch15'
import PlaceOfWorship11 from './components/PlaceOfWorship11'
import PlaceOfWorship15 from './components/PlaceOfWorship15'
import Playground11 from './components/Playground11'
import Playground15 from './components/Playground15'
import Police11 from './components/Police11'
import Police15 from './components/Police15'
import Post11 from './components/Post11'
import Post15 from './components/Post15'
import Prison11 from './components/Prison11'
import Prison15 from './components/Prison15'
import Rail11 from './components/Rail11'
import Rail15 from './components/Rail15'
import RailLight11 from './components/RailLight11'
import RailLight15 from './components/RailLight15'
import RailMetro11 from './components/RailMetro11'
import RailMetro15 from './components/RailMetro15'
import RangerStation11 from './components/RangerStation11'
import RangerStation15 from './components/RangerStation15'
import Recycling11 from './components/Recycling11'
import Recycling15 from './components/Recycling15'
import ReligiousChristian11 from './components/ReligiousChristian11'
import ReligiousChristian15 from './components/ReligiousChristian15'
import ReligiousJewish11 from './components/ReligiousJewish11'
import ReligiousJewish15 from './components/ReligiousJewish15'
import ReligiousMuslim11 from './components/ReligiousMuslim11'
import ReligiousMuslim15 from './components/ReligiousMuslim15'
import ResidentialCommunity11 from './components/ResidentialCommunity11'
import ResidentialCommunity15 from './components/ResidentialCommunity15'
import Restaurant11 from './components/Restaurant11'
import Restaurant15 from './components/Restaurant15'
import Roadblock11 from './components/Roadblock11'
import Roadblock15 from './components/Roadblock15'
import Rocket11 from './components/Rocket11'
import Rocket15 from './components/Rocket15'
import School11 from './components/School11'
import School15 from './components/School15'
import Scooter11 from './components/Scooter11'
import Scooter15 from './components/Scooter15'
import Shelter11 from './components/Shelter11'
import Shelter15 from './components/Shelter15'
import Shop11 from './components/Shop11'
import Shop15 from './components/Shop15'
import Skiing11 from './components/Skiing11'
import Skiing15 from './components/Skiing15'
import Slaughterhouse11 from './components/Slaughterhouse11'
import Slaughterhouse15 from './components/Slaughterhouse15'
import Snowmobile11 from './components/Snowmobile11'
import Snowmobile15 from './components/Snowmobile15'
import Soccer11 from './components/Soccer11'
import Soccer15 from './components/Soccer15'
import Square11 from './components/Square11'
import Square15 from './components/Square15'
import SquareStroked11 from './components/SquareStroked11'
import SquareStroked15 from './components/SquareStroked15'
import Stadium11 from './components/Stadium11'
import Stadium15 from './components/Stadium15'
import Star11 from './components/Star11'
import Star15 from './components/Star15'
import StarStroked11 from './components/StarStroked11'
import StarStroked15 from './components/StarStroked15'
import Suitcase11 from './components/Suitcase11'
import Suitcase15 from './components/Suitcase15'
import Sushi11 from './components/Sushi11'
import Sushi15 from './components/Sushi15'
import Swimming11 from './components/Swimming11'
import Swimming15 from './components/Swimming15'
import Teahouse11 from './components/Teahouse11'
import Teahouse15 from './components/Teahouse15'
import Telephone11 from './components/Telephone11'
import Telephone15 from './components/Telephone15'
import Tennis11 from './components/Tennis11'
import Tennis15 from './components/Tennis15'
import Theatre11 from './components/Theatre11'
import Theatre15 from './components/Theatre15'
import Toilet11 from './components/Toilet11'
import Toilet15 from './components/Toilet15'
import Town11 from './components/Town11'
import Town15 from './components/Town15'
import TownHall11 from './components/TownHall11'
import TownHall15 from './components/TownHall15'
import Triangle11 from './components/Triangle11'
import Triangle15 from './components/Triangle15'
import TriangleStroked11 from './components/TriangleStroked11'
import TriangleStroked15 from './components/TriangleStroked15'
import Veterinary11 from './components/Veterinary11'
import Veterinary15 from './components/Veterinary15'
import Village11 from './components/Village11'
import Village15 from './components/Village15'
import Volcano11 from './components/Volcano11'
import Volcano15 from './components/Volcano15'
import Warehouse11 from './components/Warehouse11'
import Warehouse15 from './components/Warehouse15'
import WasteBasket11 from './components/WasteBasket11'
import WasteBasket15 from './components/WasteBasket15'
import Water11 from './components/Water11'
import Water15 from './components/Water15'
import Wetland11 from './components/Wetland11'
import Wetland15 from './components/Wetland15'
import Wheelchair11 from './components/Wheelchair11'
import Wheelchair15 from './components/Wheelchair15'
import Zoo11 from './components/Zoo11'
import Zoo15 from './components/Zoo15'

export {
  Aerialway11,
	Aerialway15,
	Airfield11,
	Airfield15,
	Airport11,
	Airport15,
	AlcoholShop11,
	AlcoholShop15,
	AmericaFootball11,
	AmericaFootball15,
	AmusementPark11,
	AmusementPark15,
	Aquarium11,
	Aquarium15,
	ArtGallery11,
	ArtGallery15,
	Attraction11,
	Attraction15,
	Bakery11,
	Bakery15,
	Bank11,
	Bank15,
	Bar11,
	Bar15,
	Barrier11,
	Barrier15,
	Baseball11,
	Baseball15,
	Basketball11,
	Basketball15,
	Bbq11,
	Bbq15,
	Beer11,
	Beer15,
	Bicycle11,
	Bicycle15,
	BicycleShare11,
	BicycleShare15,
	BloodBank11,
	BloodBank15,
	Buddhism11,
	Buddhism15,
	Building11,
	Building15,
	BuildingAlt111,
	BuildingAlt115,
	Bus11,
	Bus15,
	Cafe11,
	Cafe15,
	Campsite11,
	Campsite15,
	Car11,
	Car15,
	Castle11,
	Castle15,
	Cemetery11,
	Cemetery15,
	Cinema11,
	Cinema15,
	Circle11,
	Circle15,
	CircleStroked11,
	CircleStroked15,
	City11,
	City15,
	ClothingStore11,
	ClothingStore15,
	College11,
	College15,
	Commercial11,
	Commercial15,
	Cricket11,
	Cricket15,
	Cross11,
	Cross15,
	Dam11,
	Dam15,
	Danger11,
	Danger15,
	Defibrillator11,
	Defibrillator15,
	Dentist11,
	Dentist15,
	Doctor11,
	Doctor15,
	DogPark11,
	DogPark15,
	DrinkingWater11,
	DrinkingWater15,
	Embassy11,
	Embassy15,
	EmergencyPhone11,
	EmergencyPhone15,
	Entrance11,
	Entrance15,
	EntranceAlt111,
	EntranceAlt115,
	Farm11,
	Farm15,
	FastFood11,
	FastFood15,
	Fence11,
	Fence15,
	Ferry11,
	Ferry15,
	FireStation11,
	FireStation15,
	Florist11,
	Florist15,
	Fuel11,
	Fuel15,
	Gaming11,
	Gaming15,
	Garden11,
	Garden15,
	GardenCenter11,
	GardenCenter15,
	Gift11,
	Gift15,
	Golf11,
	Golf15,
	Grocery11,
	Grocery15,
	Hairdresser11,
	Hairdresser15,
	Harbor11,
	Harbor15,
	Heart11,
	Heart15,
	Heliport11,
	Heliport15,
	Home11,
	Home15,
	HorseRiding11,
	HorseRiding15,
	Hospital11,
	Hospital15,
	IceCream11,
	IceCream15,
	Industry11,
	Industry15,
	Information11,
	Information15,
	Karaoke11,
	Karaoke15,
	Landmark11,
	Landmark15,
	Landuse11,
	Landuse15,
	Laundry11,
	Laundry15,
	Library11,
	Library15,
	Lighthouse11,
	Lighthouse15,
	Lodging11,
	Lodging15,
	Logging11,
	Logging15,
	Marker11,
	Marker15,
	MarkerStroked11,
	MarkerStroked15,
	MobilePhone11,
	MobilePhone15,
	Monument11,
	Monument15,
	Mountain11,
	Mountain15,
	Museum11,
	Museum15,
	Music11,
	Music15,
	Natural11,
	Natural15,
	Park11,
	Park15,
	ParkAlt111,
	ParkAlt115,
	Parking11,
	Parking15,
	ParkingGarage11,
	ParkingGarage15,
	Pharmacy11,
	Pharmacy15,
	PicnicSite11,
	PicnicSite15,
	Pitch11,
	Pitch15,
	PlaceOfWorship11,
	PlaceOfWorship15,
	Playground11,
	Playground15,
	Police11,
	Police15,
	Post11,
	Post15,
	Prison11,
	Prison15,
	Rail11,
	Rail15,
	RailLight11,
	RailLight15,
	RailMetro11,
	RailMetro15,
	RangerStation11,
	RangerStation15,
	Recycling11,
	Recycling15,
	ReligiousChristian11,
	ReligiousChristian15,
	ReligiousJewish11,
	ReligiousJewish15,
	ReligiousMuslim11,
	ReligiousMuslim15,
	ResidentialCommunity11,
	ResidentialCommunity15,
	Restaurant11,
	Restaurant15,
	Roadblock11,
	Roadblock15,
	Rocket11,
	Rocket15,
	School11,
	School15,
	Scooter11,
	Scooter15,
	Shelter11,
	Shelter15,
	Shop11,
	Shop15,
	Skiing11,
	Skiing15,
	Slaughterhouse11,
	Slaughterhouse15,
	Snowmobile11,
	Snowmobile15,
	Soccer11,
	Soccer15,
	Square11,
	Square15,
	SquareStroked11,
	SquareStroked15,
	Stadium11,
	Stadium15,
	Star11,
	Star15,
	StarStroked11,
	StarStroked15,
	Suitcase11,
	Suitcase15,
	Sushi11,
	Sushi15,
	Swimming11,
	Swimming15,
	Teahouse11,
	Teahouse15,
	Telephone11,
	Telephone15,
	Tennis11,
	Tennis15,
	Theatre11,
	Theatre15,
	Toilet11,
	Toilet15,
	Town11,
	Town15,
	TownHall11,
	TownHall15,
	Triangle11,
	Triangle15,
	TriangleStroked11,
	TriangleStroked15,
	Veterinary11,
	Veterinary15,
	Village11,
	Village15,
	Volcano11,
	Volcano15,
	Warehouse11,
	Warehouse15,
	WasteBasket11,
	WasteBasket15,
	Water11,
	Water15,
	Wetland11,
	Wetland15,
	Wheelchair11,
	Wheelchair15,
	Zoo11,
	Zoo15
}
  