// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class BloodBank11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M8.405 4.644h.001L5.5 1 2.593 4.644h.002A3.37 3.37 0 0 0 2 6.56a3.464 3.464 0 0 0 3.5 3.43A3.464 3.464 0 0 0 9 6.558a3.37 3.37 0 0 0-.595-1.915zM8 7H6v2H5V7H3V6h2V4h1v2h2v1z'/>
      </Svg>
    )
  }
}

export default BloodBank11
  