// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class BloodBank15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M11.2 7.1L7.5 2 3.8 7.1c-.5.7-.8 1.6-.8 2.5C3 12 5 14 7.5 14S12 12 12 9.6c0-.9-.3-1.8-.8-2.5zM10 10H8v2H7v-2H5V9h2V7h1v2h2v1z'/>
      </Svg>
    )
  }
}

export default BloodBank15
  