// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class BuildingAlt111 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M8 9.5v-5c0-.3-.2-.5-.5-.5H6V1L3 2v7.5H2v.5h7v-.5H8zm-3 0H4V3h1v6.5z'/>
      </Svg>
    )
  }
}

export default BuildingAlt111
  