// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Building11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M2 1v9h4V6h2v4h1V1H2zm3 8H3V6h2v3zm0-4H3V3h2v2zm3 0H6V3h2v2z'/>
      </Svg>
    )
  }
}

export default Building11
  