// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Campsite11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M5.92 2.19a.5.5 0 0 0-.85 0L1.5 8h-1a.42.42 0 0 0-.5.39V9.5a.49.49 0 0 0 .5.5h10a.49.49 0 0 0 .5-.5V8.39a.42.42 0 0 0-.5-.39h-1L5.92 2.19zM5.5 3l3 5h-6l3-5z'/>
      </Svg>
    )
  }
}

export default Campsite11
  