// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Circle11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M10 5.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0z'/>
      </Svg>
    )
  }
}

export default Circle11
  