// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class CircleStroked11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M5.5 0a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11zm0 1.222a4.278 4.278 0 1 0 0 8.556 4.278 4.278 0 0 0 0-8.556z'/>
      </Svg>
    )
  }
}

export default CircleStroked11
  