// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Circle15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M14 7.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z'/>
      </Svg>
    )
  }
}

export default Circle15
  