// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class City15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M13.639 4H12V1.361A.361.361 0 0 0 11.639 1h-.278a.361.361 0 0 0-.361.361V4H9.361A.361.361 0 0 0 9 4.361V10H5.363a.363.363 0 0 0-.363.363v3.275a.363.363 0 0 0 .363.362h8.276a.361.361 0 0 0 .361-.361V4.361A.361.361 0 0 0 13.639 4zM7 12H6v-1h1zm2 0H8v-1h1zm2 0h-1v-1h1zm0-2h-1V9h1zm0-2h-1V7h1zm0-2h-1V5h1zm2 6h-1v-1h1zm0-2h-1V9h1zm0-2h-1V7h1zm0-2h-1V5h1zM8 1.361A.361.361 0 0 0 7.639 1H5.361A.361.361 0 0 0 5 1.361V3H3.361A.361.361 0 0 0 3 3.361V4H1.361A.361.361 0 0 0 1 4.361v9.278a.361.361 0 0 0 .361.361H4V9h4zM3 12H2v-1h1zm0-2H2V9h1zm0-2H2V7h1zm0-2H2V5h1zm2 2H4V7h1zm0-2H4V5h1zm2 2H6V7h1zm0-2H6V5h1zm0-2H6V3h1z'/>
      </Svg>
    )
  }
}

export default City15
  