// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class City11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M9.75 3H9V1.25A.25.25 0 0 0 8.75 1h-.5a.25.25 0 0 0-.25.25V3h-.75a.25.25 0 0 0-.25.25V7H5.251A.251.251 0 0 0 5 7.251v2.5a.251.251 0 0 0 .251.249h4.5A.25.25 0 0 0 10 9.75v-6.5A.25.25 0 0 0 9.75 3zM6 8h1v1H6zm3 1H8V8h1zm0-2H8V6h1zm0-2H8V4h1zM6 1.25A.25.25 0 0 0 5.75 1h-2.5a.25.25 0 0 0-.25.25V2h-.75a.25.25 0 0 0-.25.25V3h-.75a.25.25 0 0 0-.25.25v6.5a.25.25 0 0 0 .25.25H4V6h2zM3 9H2V8h1zm0-2H2V6h1zm0-2H2V4h1zm2 0H4V4h1zm0-2H4V2h1z'/>
      </Svg>
    )
  }
}

export default City11
  