// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ClothingStore11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M2.5 1l-2 2v2h2v5h6V5h2V3l-2-2H7L5.5 4 4 1H2.5z'/>
      </Svg>
    )
  }
}

export default ClothingStore11
  