// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ClothingStore15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M3.5 1L0 4v3h2.9l.1 7h9V7h3V4l-3.5-3H10L7.5 5 5 1H3.5z'/>
      </Svg>
    )
  }
}

export default ClothingStore15
  