// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg
} from 'react-native-svg'

class College11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'/>
    )
  }
}

export default College11
  