// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Commercial11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M0 5a4.71 4.71 0 0 1 1-3h9a4.71 4.71 0 0 1 1 3H0zm2 1v5h4V7h2v4h1V6H2zm3 3H3V7h2v2z'/>
      </Svg>
    )
  }
}

export default Commercial11
  