// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Defibrillator11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M1.42 4.795C-.213 1.53 3.933-.65 5.512 2.615c1.58-3.266 5.725-1.086 4.092 2.18-.023.038-.048.074-.071.111H8.387l-.828-1.654a.65.65 0 0 0-1.118 0L5 6.134l-.441-.882A.624.624 0 0 0 4 4.906H1.491l-.071-.11zM8 6.156a.624.624 0 0 1-.559-.345L7 4.929 5.559 7.81a.624.624 0 0 1-1.118 0l-.828-1.654H2.301a24.227 24.227 0 0 0 2.897 3.45l.015.015a.44.44 0 0 0 .622-.016 24.229 24.229 0 0 0 2.89-3.449H8z'/>
      </Svg>
    )
  }
}

export default Defibrillator11
  