// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Farm15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M8 7L5 5 2 7 1 9v4h2v-2h4v2h2V9zM6 9H4V7h2v2zm8 4h-3V3.5a1.5 1.5 0 0 1 3 0V13z' fill='#010101'/>
      </Svg>
    )
  }
}

export default Farm15
  