// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Farm11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M6 5L4 4 2 5 1 7v3h1.5V8h3v2H7V7zM5 7H3V5.5h2V7z' fill='#231f20'/><Path d='M10 2a1 1 0 0 0-2 0v8h2V2z' fill='#010101'/>
      </Svg>
    )
  }
}

export default Farm11
  