// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Heart11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M10.06 4.76a27 27 0 0 1-4.2 5.36.49.49 0 0 1-.71 0A27.003 27.003 0 0 1 .94 4.76C-.88 1.12 3.74-1.31 5.5 2.33c1.76-3.64 6.38-1.21 4.56 2.43z'/>
      </Svg>
    )
  }
}

export default Heart11
  