// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Home15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M2 13.75a.25.25 0 0 0 .25.25H6v-3h3v3h3.75a.25.25 0 0 0 .25-.25V8H2zm11.932-7.171L13 5.76V2a1 1 0 0 0-2 0v2L7.682 1.09a.25.25 0 0 0-.353-.011l-.011.011-6.25 5.464a.25.25 0 0 0 .179.421L3 7h10.749a.25.25 0 0 0 .183-.421z'/>
      </Svg>
    )
  }
}

export default Home15
  