// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Home11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M10 4.75a.25.25 0 0 1-.25.25h-8.5A.25.25 0 0 1 1 4.75a.261.261 0 0 1 .08-.19l4.237-3.454.016-.016a.248.248 0 0 1 .35.016L8 2.995V1.5a.5.5 0 0 1 1 0v2.31l.92.75a.261.261 0 0 1 .08.19zm-8 5a.248.248 0 0 0 .246.25H5V8h1v2h2.752A.248.248 0 0 0 9 9.752V6H2z'/>
      </Svg>
    )
  }
}

export default Home11
  