// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Hospital11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M10 4H7V1a1.08 1.08 0 0 0-1-1H5a1.08 1.08 0 0 0-1 1v3H1a1.08 1.08 0 0 0-1 1v1a1.08 1.08 0 0 0 1 1h3v3a1.08 1.08 0 0 0 1 1h1a1.08 1.08 0 0 0 1-1V7h3a1.08 1.08 0 0 0 1-1V5a1 1 0 0 0-1-1z'/>
      </Svg>
    )
  }
}

export default Hospital11
  