// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Hospital15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M7 1c-.6 0-1 .4-1 1v4H2c-.6 0-1 .4-1 1v1c0 .6.4 1 1 1h4v4c0 .6.4 1 1 1h1c.6 0 1-.4 1-1V9h4c.6 0 1-.4 1-1V7c0-.6-.4-1-1-1H9V2c0-.6-.4-1-1-1H7z' fill='#010101'/>
      </Svg>
    )
  }
}

export default Hospital15
  