// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Industry15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M14 1v12H1V8.72a.5.5 0 0 1 .17-.37l3-3.22a.5.5 0 0 1 .83.38v3l3.16-3.37a.5.5 0 0 1 .84.37V11h3V1h2z'/>
      </Svg>
    )
  }
}

export default Industry15
  