// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Industry11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M10 1v8H1V6l2.11-1.78c.32-.32.89-.31.89.14V6l2.13-1.86A.5.5 0 0 1 7 4.5V8h2V1h1z'/>
      </Svg>
    )
  }
}

export default Industry11
  