// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Karaoke11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M4.5 4.4l-2 2-1 1c-.5.4-.6 1.1-.3 1.7l.6.7c.6.4 1.3.2 1.7-.3l1-1 2-2-2-2.1zM3.1 8.5l-.6-.7 2-2 .7.7-2.1 2zM5 2l1-1h3l1 1v3L9 6H8L5 3V2z'/>
      </Svg>
    )
  }
}

export default Karaoke11
  