// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Monument15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M7.5 0L6 2.5v7h3v-7L7.5 0zM3 11.5V15h9v-3.5L10.5 10h-6L3 11.5z'/>
      </Svg>
    )
  }
}

export default Monument15
  