// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Monument11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M5.5 0L4 2v4.5h3V2L5.5 0zM3 7L2 8v3h7V8L8 7H3z'/>
      </Svg>
    )
  }
}

export default Monument11
  