// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Pitch11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M4 2a1 1 0 1 1 0-2 1 1 0 0 1 0 2zm6.5 6H9L8 5 7 3.25 8 3l2.3 1a.531.531 0 0 0 .36-1L8 2H6L4 3 3 4H1.47a.5.5 0 0 0 0 1H4l1-1 1 2-2 1v3.5a.5.5 0 0 0 1 0V7.39L7 7l1 2h2.5a.5.5 0 0 0 0-1z'/>
      </Svg>
    )
  }
}

export default Pitch11
  