// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class PlaceOfWorship15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M7.5 0l-2 2v2h4V2l-2-2zm-2 4.5L4 6h7L9.5 4.5h-4zM2 6.5a1 1 0 0 0-1 1V13h2V7.5a1 1 0 0 0-1-1zm2 0V13h7V6.5H4zm9 0a1 1 0 0 0-1 1V13h2V7.5a1 1 0 0 0-1-1z'/>
      </Svg>
    )
  }
}

export default PlaceOfWorship15
  