// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Post15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M14 6.5V12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6.5a.5.5 0 0 1 .5-.5.49.49 0 0 1 .21 0l5.79 4 5.8-4a.488.488 0 0 1 .2 0 .5.5 0 0 1 .5.5zM1.25 3.92l.08.08L7.5 8l6.19-4h.06a.49.49 0 0 0 .25-.5.5.5 0 0 0-.5-.5h-12a.5.5 0 0 0-.5.5.49.49 0 0 0 .25.42z'/>
      </Svg>
    )
  }
}

export default Post15
  