// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Prison11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M2 1v9h7V1H2zm1 1h1v3H3V2zm2 0h1v3H5V2zm2 0h1v2H7V2zm.5 3a.5.5 0 1 1 0 1 .5.5 0 0 1 0-1zM3 6h1v3H3V6zm2 0h1v3H5V6zm2 1h1v2H7V7z'/>
      </Svg>
    )
  }
}

export default Prison11
  