// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class RangerStation15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M9 .5l-2 1v3.773L2 8v6h4v-4h3v4h4V8L8 5.273V4l1-.5 2 1 2-1v-3l-2 1-2-1z'/>
      </Svg>
    )
  }
}

export default RangerStation15
  