// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class RangerStation11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M6.334 0L5 1v3L1 6.055V10h3V7h3v3h3V6.055L6 4V2.25L6.334 2l1.332 1L9 2V0L7.666 1 6.334 0z'/>
      </Svg>
    )
  }
}

export default RangerStation11
  