// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ReligiousChristian11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M4.5 0v3H2v2h2.5v6h2V5H9V3H6.5V0h-2z'/>
      </Svg>
    )
  }
}

export default ReligiousChristian11
  