// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ReligiousJewish15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M15 12H9.78L7.5 15l-2.26-3H0l2.7-4L0 4h5.3l2.2-4 2.34 4H15l-2.56 4L15 12z'/>
      </Svg>
    )
  }
}

export default ReligiousJewish15
  