// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ReligiousChristian15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M6 .955V4H3v3h3v8h3V7h3V4H9V1c0-1-.978-1-.978-1H6.99S6 0 6 .955z'/>
      </Svg>
    )
  }
}

export default ReligiousChristian15
  