// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class ReligiousJewish11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M11 8H7.1l-1.6 3-1.6-3H0l1.95-2.5L0 3h3.9l1.6-3 1.6 3H11L9.05 5.5 11 8z'/>
      </Svg>
    )
  }
}

export default ReligiousJewish11
  