// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Roadblock11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M5.5 0a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11zM2 4.5h7v2H2v-2z'/>
      </Svg>
    )
  }
}

export default Roadblock11
  