// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class School11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M8.5 9V8H10V6H7.5V5H10V3H8.5V2H10V1H6v9h4V9H8.5zM4 7H1V1h3v6zm0 1l-1.5 2L1 8h3z'/>
      </Svg>
    )
  }
}

export default School11
  