// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Shelter15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M4 7v5h9.5v2H2V7.78l-1 .38V6l13-5v2.14L4 7z'/>
      </Svg>
    )
  }
}

export default Shelter15
  