// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Shelter11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M4 5v3h6v2H2V5.67L1 6V4l9-3v2L4 5z'/>
      </Svg>
    )
  }
}

export default Shelter11
  