// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class SquareStroked15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M12.7 2.3v10.4H2.3V2.3h10.4M13 1H2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z'/>
      </Svg>
    )
  }
}

export default SquareStroked15
  