// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class SquareStroked11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M9.19 1H1.81a.81.81 0 0 0-.81.81v7.38c0 .447.363.81.81.81h7.38a.81.81 0 0 0 .81-.81V1.81A.81.81 0 0 0 9.19 1zM2 2h7v7H2V2z'/>
      </Svg>
    )
  }
}

export default SquareStroked11
  