// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Star11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M5.4 0L4 3.5H0l3 3L1.5 11l3.9-2.6L9.5 11 8 6.5l3-3H7L5.4 0z'/>
      </Svg>
    )
  }
}

export default Star11
  