// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Teahouse11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M6.2 4C7.4 3.7 8 3.7 8 2.5c0-.6-.4-.8-1.6-1.3C5.6.9 5.3.9 5.3.1c-.3.9-.1 1.2.8 1.7 2 1 .1 2.2.1 2.2zM3.9 4c.7-.2 1.1-.2 1.1-.9 0-.4-.3-.5-1-.9-.5-.2-.7-.7-.7-1.2-.2.6-.1 1.3.5 1.6 1.2.6.1 1.4.1 1.4zM9 5H2l1 3c.3.4.6.7 1 1v2h3V9c.4-.3.7-.6 1-1l1-3z'/>
      </Svg>
    )
  }
}

export default Teahouse11
  