// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Volcano11 extends React.PureComponent {
  render () {
    return (
      <Svg width='11' height='11' viewBox='0 0 11 11'>
        <Path d='M3 1l1.5 3h2L8 3V2L6 3V1h-.5L5 2.5 3.5 1H3zm.522 4L1.023 9.16c-.223.37.044.84.476.84h8c.432 0 .7-.47.477-.84L7.479 5H7v.5a.499.499 0 1 1-1 0 .5.5 0 0 0-1 0v2a.499.499 0 1 1-1 0V5h-.478z'/>
      </Svg>
    )
  }
}

export default Volcano11
  