// AUTOGENERATED DO NOT MODIFY
import React from 'react'

import {
  Svg,
	Path
} from 'react-native-svg'

class Water15 extends React.PureComponent {
  render () {
    return (
      <Svg width='15' height='15' viewBox='0 0 15 15'>
        <Path d='M7.49 15A5.84 5.84 0 0 1 2 9.5C2 6.6 6.25 1.66 7.49 0c1.24 1.66 5 6.59 5 9.49S10.17 15 7.49 15z'/>
      </Svg>
    )
  }
}

export default Water15
  